#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition=solve1
#SBATCH --exclusive
#SBATCH --output=03_%x_export_%j.out
#SBATCH --job-name=RC_EX033_half





ENSIGHT=TRUE
SP=FALSE		#To run single precision set as TRUE
VERSION=of2206 	#change to of2112 or of2206 if desired    
cd $SLURM_SUBMIT_DIR 	#changes to submission directory
#changes solve precision to SP if true
BINFORCE="~/openFoam/scripts/dist/binPlotForces_V2_0/binPlotForces_V2_0"
if [ SP = "TRUE" ]; then
	echo "Running Solve Script in SP!"
	. ~/openFoam/CODEHOST/OFSource/$VERSION/etc/bashrc WM_PRECISION_OPTION=SP
	
else
	echo "Running Solve Script in DP!"
	. ~/openFoam/CODEHOST/OFSource/$VERSION/etc/bashrc WM_PRECISION_OPTION=DP
fi
	. $WM_PROJECT_DIR/bin/tools/RunFunctions
	echo "Removing old logs..."
	rm -r log.exportScript
	cp system/controlDictExport system/controlDict
	echo "Exporting post fields..."
	
	/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec simpleFoam -postProcess -parallel -latestTime -fields "(pMean UMean phiMean nuTildaMean omegaMean kMean nutMean U p phi nuTilda omega k nut)" >> log.meanExports
	if [ $? -eq 0 ]; then
		if [ $ENSIGHT = "TRUE" ]; then
			echo "Running foamToEnsight"
			/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec foamToEnsight -parallel -latestTime -noZero >> log.EnSight
		fi
	fi
	if [ $? -eq 0 ]; then
	
		if [ -d postProcessing/surfaces ]; then
			sbatch postProScript
			echo "Export successful!"
		fi
	else
		echo "Export threw an error code!"
	fi
	cp system/controlDictSimple system/controlDict	
	echo "Export complete, check log file for errors."

	

	
	
	
#------------------------------------------------------------------------------
