#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=36
#SBATCH --partition=solve1
#SBATCH --output=01_%x_meshing_%j.out
#SBATCH --exclusive
#SBATCH --job-name=RC_MS033_half 
       
      
	  
	  
	  
	  
	  
SP=FALSE		#To run single precision set as TRUE
VERSION=of2206 	#change to of2112 or of2206 if desired
       
       
cd $SLURM_SUBMIT_DIR 	#changes to submission directory
#changes solve precision to SP if true
if [ SP = "TRUE" ]; then
	echo "Running Solve Script in SP!"
	. ~/openFoam/CODEHOST/OFSource/$VERSION/etc/bashrc WM_PRECISION_OPTION=SP
	#export SP="TRUE"
	
else
	
	echo "Running Solve Script in DP!"
	. ~/openFoam/CODEHOST/OFSource/$VERSION/etc/bashrc WM_PRECISION_OPTION=DP
	#export DP="FALSE"
	
fi
	
	. $WM_PROJECT_DIR/bin/tools/RunFunctions
	
	rm -r processor*
	rm -r log.snappyHexMesh
	rm -r log.surfaceFeatureExtract
	rm -r log.blockMesh
	rm -r log.decomposePar
	rm -r log.renumberMesh
	rm -r log.checkMesh

	if [ -f system/controlDictSimple ]; then
		cp system/controlDictSimple system/controlDict
	elif [ -f system/controlDictPiso ]; then
		cp system/controlDictPiso system/controlDict
	elif [ -f system/controlDictPotential ]; then
		cp system/controlDictPotential system/controlDict
	else
		exit 1
	fi
	if [ $? != 0 ]; then exit 1; fi
	echo "running surfaceFeatureExtract..."
	~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec surfaceFeatureExtract >> log.surfaceFeatureExtract
	if [ $? != 0 ]; then exit 1; fi
	echo "running blockMesh..."
	~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec blockMesh >> log.blockMesh
	if [ $? != 0 ]; then exit 1; fi
	echo "running decomposePar..."
	~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec decomposePar -copyZero >> log.decomposePar
	
	if [ -f system/fvSchemesSimple ]; then
		cp system/fvSchemesSimple system/fvSchemes
		cp system/fvSolutionSimple system/fvSolution
	elif [ -f system/fvSchemesPiso ]; then
		cp system/fvSchemesPiso system/fvSchemes
		cp system/fvSolutionPiso system/fvSolution
	else
		echo "ERROR! Unable to find the right fvSchemes or fvSolution files for the appropriate simulation type!"
		exit 1
	fi
	if [ $? != 0 ]; then exit 1; fi
	echo 'running snappyHexMesh...'
	/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec snappyHexMesh -parallel -overwrite >> log.snappyHexMesh
	if [ $? != 0 ]; then exit 1; fi
	echo 'running renumberMesh...'
	/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec renumberMesh -parallel -constant -overwrite >> log.renumberMesh
	if [ $? != 0 ]; then exit 1; fi
	echo 'running checkMesh...'
	/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec checkMesh -parallel >> log.checkMesh
	if [ $? != 0 ]; then exit 1; fi
	cp system/controlDictSimpleFoam system/controlDict
	echo 'Exporting mesh...'
	/usr/bin/mpirun ~/openFoam/CODEHOST/OFSource/$VERSION/bin/tools/foamExec postProcess -func postMeshSurfaces -parallel -constant >> log.postMeshSurfaces
	if [ $? != 0 ]; then exit 1; fi
	if [[ -d postProcessing/postMeshSurfaces ]]; then
		if [[ -d postMeshPostProcessing ]]; then
			rm -r postMeshPostProcessing
		fi
		mkdir postMeshPostProcessing
		mv postProcessing/postMeshSurfaces postMeshPostProcessing/.
	fi
	
	
	
