import sys
import os
from shutil import copytree,ignore_patterns,copy
import glob
import time
import argparse


parser = argparse.ArgumentParser(
                    prog='Copy Trial V3.0',
                    description='Copies the case from one to another, can copy just mesh or entire case. Can also copy empty trial.',
                    epilog='Read the documentation for more information on how to use this')

parser.add_argument('-t','--trial',required=True,nargs='+',help='selects the source and destination trial, the first trial is always the source, the rest can be of any number of trials')
parser.add_argument('--mesh',action='store_true',help='copies the case and the mesh in decomposed format')
parser.add_argument('--latestTimeZero',action='store_true',help='copies the case and sets the final timestep to 0 to enable final time as a seed case')
# parser.add_argument('--yscaling',default = 'default',help = 'sets the y scaling factor for the plots',
# 					choices = ['default','matDefault']) 
# parser.add_argument('--saveFormat',default = 'png',help = 'sets the format for the saved plots, by default [png]',
# 					choices = ['png','eps','jpeg']) 
# parser.add_argument('--avgTime',help = 'manually set averaging start time',type=float) 
# parser.add_argument('--nchunks',default = 10,help = 'manually set chunk amount start time',type=int) 



args = parser.parse_args()
print("###### copyTrial-v3.0 ######")
path = os.path.split(os.getcwd())[0]
case = os.path.split(os.getcwd())[1]
casesDir = os.getcwd()


#Check to see if in case folder
if not casesDir.endswith('CASES'):
	print(casesDir)
	sys.exit('Not in CASES folder!')

# total selected trials must be greater than 1
if len(args.trial) < 2: 
	sys.exit('ERROR! Need atleast 1 destination case!')

def main():

	destTrialArray = args.trial[1:]
	sourceTrial = args.trial[0]
	
	
	
	for destTrial in destTrialArray:
		print('Copying trials: %s to %s' % (sourceTrial,destTrial))
		destPath = "%s/%s" % (casesDir,destTrial)
		sourcePath = "%s/%s" % (casesDir,sourceTrial)
		
		if not os.path.isdir(sourcePath):
			sys.exit("ERROR! Source directory does not exist!") #checking if the source directory is correct and exists
		
		if os.path.isdir(destPath):
			sys.exit("ERROR! Destination directory already exists!") #checking if the destination directory exists
		#copyRequired(casesDir,sourcePath,destPath)
		
		copyRequired(casesDir=casesDir,sourcePath = sourcePath,destPath=destPath)

		if args.mesh == True or args.latestTimeZero == True:
			print('\tCopying mesh from %s file to %s...' % (sourceTrial,destTrial))
			copyMesh(casesDir,sourcePath,destPath)
			for item in ['log.checkMesh','log.snappyHexMesh']:
				os.system("cp %s/%s %s/%s" % (sourcePath,item,destPath,item))
		if args.latestTimeZero == True:
			copyLatestTimeToZero(casesDir=casesDir,sourcePath = sourcePath,destPath=destPath)
			

def copyRequired(casesDir,sourcePath,destPath):

	print("\tCopying required files...")
	copytree(sourcePath,destPath,symlinks=True,ignore=ignore_patterns('*.eMesh', '*.obj','EnSight','*.save',
																   'fullCaseSetupDict','polyMesh','extendedFeatureEdgeMesh',
																   'processor*','log.*','*.foam','postProcessing','*.out','*PyFoamHistory*',
																   '*.csv','*.stl','*.png','*.pdf','postProReport','*Script*')) 
																   #copying the required files by omitting the files that will be generated by openfoam
	print("Done!")


#Mesh copy function
def copyMesh(casesDir,sourcePath,destPath):

	sourceList = os.listdir(sourcePath) #listing all the files in the case
	processorArray = []	#initializing the array
	for file in sourceList:
		if file.startswith("processor"):
			processorArray.append(file) #add directory to name array if the directory starts with processor
	for processor in processorArray:
		print("\t\tCopying mesh to %s" % (processor))
		copytree("%s/%s/constant" % (sourcePath,processor),"%s/%s/constant" % (destPath,processor)) #copying the mesh in each processor over


def copyLatestTimeToZero(casesDir,sourcePath,destPath):
	sourceList = os.listdir(sourcePath) #listing all the files in the case
	processorArray = []	#initializing the array
	for file in sourceList:
		if file.startswith("processor"):
			processorArray.append(file) #add directory to name array if the directory starts with processor
	#checking for the latest time in processor
	#look in processor0, assuming all processors have the same time
	availableTimes = os.listdir(os.path.join(sourcePath,processorArray[0]))
	if len(availableTimes) > 0:
		timeArray = []
		for time in availableTimes:
			try: 
				timeArray.append(float(os.path.split(time)[1]))
			except:
				continue
		latestTime = max(timeArray)
		print(latestTime)



		
	# for processor in processorArray:
	# 	print("\t\tCopying mesh to %s" % (processor))
	# 	copytree("%s/%s/constant" % (sourcePath,processor),"%s/%s/constant" % (destPath,processor)) #copying the mesh in each processor over

main()




	

		





