# Standard modules
import os, time, sys, platform, multiprocessing

# Numeca modules
from fidelity import project
from fidelity import gui
from fidelity import geometry
from fidelity import domain
from fidelity import meshing
from fidelity import material
from fidelity import simulation
from fidelity import analysis
from fidelity.plugins import hexstream_parameters
from fidelity.base import Point

#caseSetup modules
import sys
import os
import argparse as argparse
import configparser
import numpy as np
import ast
from pathlib import Path
import shutil
import gzip
import socket
import subprocess

path = os.path.split(os.getcwd())[0]
case = os.path.split(os.getcwd())[1]

jobPath = os.path.abspath(os.path.join(path,os.pardir)) #path of the job i.e. 100001
rootDir = Path(__file__).parents[1]
templateBaseLoc = "%s/setupTemplates" % (rootDir) 

addonKeyWords = ['POR','REFX','WAKE','GEOMX','ROTA','MOVG','IDOM','MRFG']
cleanUpGeom = []

def main():
    getTemplateType()
    defaultDict = getGlobalDefaults()
   
    caseSetupDict,writeCaseSetupDict,fullCaseSetupDict = getCaseSetup(defaultDict)
    for section in fullCaseSetupDict.keys():
        if 'GEOMETRY' in section:
            continue
        print('\t' + section)
        for var in fullCaseSetupDict[section].keys():
            print('\t\t' + var + ' = ' + str(fullCaseSetupDict[section][var]).replace('[','')
                                                                             .replace(']','')
                                                                             .replace(',','')
                                                                             .replace('\'',''))
    geomDict = geomToDict(fullCaseSetupDict)
    baseSize = float(fullCaseSetupDict['BC_SETUP']['BASE_CELL_SIZE'][0])
    refTable = getPIDRefTable(os.path.join(fidelityTemplateLoc,'ref_tables'),baseSize)

    print('\t\tFound %s geometries!' % (len(geomDict.keys())))
    for geom in geomDict.keys():
        print('\t\t' + geom)
        for var in geomDict[geom].keys():
            print('\t\t\t%s: %s' % (var,geomDict[geom][var]))
    
    geomDict = unzipGeomFile(geomDict) # returns an updated geomDict with the unzipped files
    hosts,cpus = get_hosts_and_cpus()

    #start Fidelity
    print('\nStarting fidelityMeshing...')
    print("\tOpening DBS template...")
    project.open_template('DBS')
    print("\tSaving file as fidelity_%s..." % (case))
    project_file="%s/%s/fidelity_%s" % (path,case,case)
    project.save_project_as(project_file)

    r_options = geometry.ImportResourceOptions()
    r_options._parallel = True
    r_options._machines             = hosts
    r_options._threads              = cpus


    #import domain generated by blockMesh
    importDomain(r_options)
    #import other geometries
    importGeometries(geomDict,r_options)

    #creating fluid domain by getting assembly of all geometries and domains
    print('\n\tCreating fluids domain...')
    fluidDomain = createFluidDomain(fullCaseSetupDict)
    createMeshSetup(fluidDomain,fullCaseSetupDict,geomDict,refTable)



    
    print('Saving Fidelity project...')
    project.save_project()
    print('Meshing complete! Finishing up...')

    cleanUpUnzippedGeomFiles(cleanUpGeom)

def importGeometries(geomDict,r_options):
    print('\n\tImporting geometries to FIDELITY...')
    geomLoc = 'constant/triSurface'
    for geom in geomDict.keys():
        print('\t\t%s' % (geom))
        geometry.import_geometry(os.path.join(geomLoc, geom), resource_options=r_options)


def createFluidDomain(fullCaseSetupDict):
    listOfAssemblies = geometry.get_top_assemblies()
    bcDict = {'half':{'x-min':'Inlet',
                      'x-max':'Outlet',
                      'y-min':'Wall',
                      'y-max':'Mirror',
                      'z-min':'Wall',
                      'z-max':'Wall',},
              'full':{'x-min':'Inlet',
                      'x-max':'Outlet',
                      'y-min':'Inlet',
                      'y-max':'Outlet',
                      'z-min':'Wall',
                      'z-max':'Wall',}}
    symmetryType = fullCaseSetupDict['GLOBAL_SIM_CONTROL']['SIM_SYM'][0]
    print('\t\tCreating fluid domain with %s symmetry!' % (symmetryType))
       
    fD = domain.create_domain(listOfAssemblies,'internal')
    seedPoint = np.array(fullCaseSetupDict['GLOBAL_REFINEMENT']['LOC_IN_MESH'],dtype=float)
    print('\t\tSetting seed point: %s' % (seedPoint))
    fD.set_seed_point(seedPoint[0],seedPoint[1],seedPoint[2])
    print('\t\tSetting BC type to domain:')
    for assy in fD.get_root_assemblies():
        if 'domain' in assy.get_name().lower():
            for surface in assy.get_surfaces():
                #print('\t\t\tChecking %s for BC type...' % (surface.get_name()))
                try:
                    bcType = bcDict[symmetryType][surface.get_name()]
                    print('\t\t\tSetting %s to %s' % (surface.get_name(),bcType))
                    fD.set_boundary_type(surface.get_name(),bcType)
                except Exception as e:
                    print(e)
                    print('\t\t\tNo BC type found for %s, defaulting to Wall!' % (surface.get_name()))
                    fD.set_boundary_type(surface.get_name(),'Wall')
    return fD

def createMeshSetup(fluidDomain,fullcaseSetupDict,geomDict,refTable):
    print('\n\tCreating mesh setup...')
    mesh_setup = meshing.create_mesh_setup(fluidDomain, 'meshSetup', mesher_name='Hexpress')
    mesh_setup.set_cells_type('Full hexa')
    baseMeshSize = float(fullcaseSetupDict['BC_SETUP']['BASE_CELL_SIZE'][0])
    mesh_setup.set_initial_cell_size(baseMeshSize)
    mesh_setup.set_far_field_treatment('Auto')
    mesh_setup.set_buffer_insertion('Cross through', 130)
    mesh_setup.set_initial_mesh_type('Cartesian')
    mesh_setup.set_close_viscous_layers_based_on_openfoam_skewness(True, value=4.0)
    mesh_setup.enable_compute_OpenFOAM_quality_criteria()
    mesh_setup.enable_compute_Fidelity_quality_criteria()
    mesh_setup.enable_capturing_of_corners_of_degree_3_4()
    mesh_setup.set_improve_quality_based_on(True,value='OpenFOAM')
    #mesh_setup.set_improve_quality_based_on(True,value='PBS', allow_deviation_from_geometry=False)
    mesh_setup.set_auto_edge_proximity_mode('Fine')
    mesh_setup.set_auto_edge_proximity(True,min_cell_size=0.001,diffusion=2)

    mesh_setup = createRefinementRegion(templateLoc, fullcaseSetupDict,mesh_setup,fluidDomain,geomDict)
    mesh_setup = setGeometryRefinement(mesh_setup,geomDict,fluidDomain,fullcaseSetupDict,refTable)


def setGeometryRefinement(meshSetup,geomDict,fluidDomain,fullCaseSetupDict,refTable):
    nonGeomList = ['domain','ref','idom']
    minRefLevel = int(fullCaseSetupDict['GLOBAL_REFINEMENT']['MIN_GEOM_LEVEL'][0])
    featEdgeLevelInc = int(fullCaseSetupDict['GLOBAL_REFINEMENT']['FEAT_EDGE_LEVEL_INC'][0])
    print('\n\t\tSetting global min refinement level: %s' % (minRefLevel))
    for assy in fluidDomain.get_root_assemblies():
        if any(x in assy.get_name().lower() for x in nonGeomList):
            continue
        else:
            for geom in geomDict.keys():
                if assy.get_name() in geom:
                    geomRef = int(geomDict[geom]['refinement'][0])
                    print('\t\t\tAttempting to set level %s for %s' % (geomRef,assy.get_name()))
                    if geomRef < minRefLevel:
                        print('\t\t\t\tGeometry assigned refinement is less than global min, using global min instead!')
                        geomRef = minRefLevel
            meshSetup.set_uniform_refinement(assy,'Refinement level',geomRef)

        for surf in assy.get_surfaces():
            for key in refTable.keys():
                #going through each key word, if key word is in pid name, that ref table is assigned
                if key in surf.get_name():
                    pidRefTable = refTable[key]
                    maxCellSize = refTable[key]['maximum_surface_length']
                    minCellSize = refTable[key]['curvature_minimum_length']


    return meshSetup


    

def createRefinementRegion(templateLoc,fullCaseSetupDict,meshSetup,fluidDomain,geomDict):

    refinementName = fullCaseSetupDict['GLOBAL_REFINEMENT']['DEFAULT_WAKE_REF'][0]
    if refinementName.lower() == 'true':
        refinementName = 'defaultWake'
    refinementPath = os.path.join(templateLoc,'defaultRefinements',refinementName)
    #check if wake config path exists
    if os.path.exists(refinementPath):
        wakeRefConfig = configparser.ConfigParser()
        wakeRefConfig.optionxform = str
        try:
            wakeRefConfig.read_file(open(refinementPath))
        except:
            print('ERROR! wake configuration is invalid!\nPath: %s' % (refinementPath))
            sys.exit()
        wakeRefConfigSections = wakeRefConfig.sections()
        print('\n\t\tCreating wake boxes: %s' % (", ".join(wakeRefConfigSections)))
    else:
        print('ERROR! wake configuration is invalid!\nPath: %s' % (refinementPath))
        sys.exit()

    wakeDict = {}
    for wake in wakeRefConfig.sections():
        print('\t\t\t%s' %(wake))
        min = np.array(wakeRefConfig[wake]['MIN'].split(' '),dtype=float)
        max = np.array(wakeRefConfig[wake]['MAX'].split(' '),dtype=float)
        print('\t\t\t\tMin: %s'% (min))
        print('\t\t\t\tMax: %s'% (max))
        size = int(wakeRefConfig[wake]['REF_LEVEL'][0])
        baseSize = float(fullCaseSetupDict['BC_SETUP']['BASE_CELL_SIZE'][0])
        wakeDict[wake] = geometry.create_box(min, max, wake)
        wakeVol = meshSetup.add_refinement_volume(wakeDict[wake])
        wakeVol.set_refinement_region('Volume')
        wakeVol.set_isotropic_refinement('Cell size', size, diffusion=2)
        
    print('\n\t\tChecking for refinement geometries...')
    for assy in fluidDomain.get_root_assemblies():
        if 'REF-' in assy.get_name():
            print('\t\t\tFound refinement geometry: %s' % (assy.get_name()))
            for geom in geomDict.keys():
                if assy.get_name() in geom:
                    refLevel = geomDict[geom]['refinement']
                    boundingBox = assy.get_bounding_box()
                    width = boundingBox.width()
                    height = boundingBox.height()
                    depth = boundingBox.depth()
                    print('\t\t\t\tWidth: %1.3fm, Height: %1.3fm, Depth: %1.3fm' % (width, height, depth))
                    print('\t\t\t\tSetting refinement level to: %s' % (refLevel))
                    wakeVol = meshSetup.add_refinement_volume(assy)
                    wakeVol.set_refinement_region('Volume')
                    wakeVol.set_isotropic_refinement('Refinement level', refLevel, diffusion=2)
        elif 'REFX-' in assy.get_name():
            print('\t\t\tFound refinement geometry: %s' % (assy.get_name()))
            for geom in geomDict.keys():
                if assy.get_name() in geom:
                    refLevel = fullCaseSetupDict[geom.split('.')[0]]['REF_LEVEL'][0]
                    boundingBox = assy.get_bounding_box()
                    width = boundingBox.width()
                    height = boundingBox.height()
                    depth = boundingBox.depth()
                    print('\t\t\t\tWidth: %1.3fm, Height: %1.3fm, Depth: %1.3fm' % (width, height, depth))
                    print('\t\t\t\tSetting refinement level to: %s' % (refLevel))
                    wakeVol = meshSetup.add_refinement_volume(assy)
                    wakeVol.set_refinement_region('Volume')
                    wakeVol.set_isotropic_refinement('Refinement level', refLevel, diffusion=2)

    print('\n\t\tSummary of refinement regions:')
    for refinement in meshSetup.get_refinement_volumes():
        print('\t\t\tRefinement region: %s, Type: %s' % (refinement.get_name(), refinement.get_refinement_region()))    
    return meshSetup

        

def getPIDRefTable(refTablePath,baseSize):

    print('\t\tImporting PID refinement tables!')
    with open(refTablePath, "r") as data:
        refTable = ast.literal_eval(data.read())
    
    for key in refTable.keys():
        for var in refTable[key].keys():
            if 'name' in var:
                continue
            try:
                level = int(refTable[key][var])
            except:
                sys.exit('ERROR! Unable to convert level string to int() in ref_table, please check entry!')
            size = calculateCellSize(level,baseSize)
            refTable[key][var] = size

    for keyWord in refTable.keys():
        print('\t\t\t',keyWord)
        for var in refTable[keyWord].keys():
            print('\t\t\t\t',var,": ",refTable[keyWord][var])
    return refTable

def calculateCellSize(level,baseSize):
    return (baseSize)/(2**level)


def get_hosts_and_cpus():
    """
    Returns two lists:
        hosts: list of hostnames
        cpus : CPUs available on each host
    """

    # Running inside Slurm
    if "SLURM_JOB_NODELIST" in os.environ:

        nodelist = os.environ["SLURM_JOB_NODELIST"]

        # Expand node list
        hosts = subprocess.check_output(
            ["scontrol", "show", "hostnames", nodelist],
            text=True
        ).strip().split("\n")

        # CPUs per node
        cpus_on_node = int(os.environ.get("SLURM_CPUS_ON_NODE", 1))

        cpus = [cpus_on_node] * len(hosts)

        return hosts, cpus

    # Local fallback
    host = socket.gethostname()
    cpus = multiprocessing.cpu_count()

    return [host], [cpus]

def importDomain(r_options):
    print('\t\tCreating blockMesh to import to FIDELITY...')
    os.system('cp system/controlDictPotential system/controlDict;blockMesh;foamToSurface constant/triSurface/domain.stl')
    geometry.import_geometry('constant/triSurface/domain.stl',resource_options=r_options)
    

def cleanUpUnzippedGeomFiles(cleanUpGeom):
    geomLoc = 'constant/triSurface'
    for geom in cleanUpGeom:
        print('\t\tRemoving unzipped geometry file: %s' % (geom.replace('.gz','')))
        os.remove(os.path.join(geomLoc,geom.replace('.gz','')))
    
def unzipGeomFile(geomDict):
    '''
        Checks for gzipped geometry
            - if it finds them,, upzips them and updates the geomDict to point to the unzippe dfile.
            - fidelity does not read in .gz files!
    '''
    print('\n\tChecking for zipped geometry files...')
    global cleanUpGeom
    geomLoc = 'constant/triSurface'
    for geom in geomDict.keys():
        if geom.endswith('.gz'):
            print('\t\tUnzipping geometry file: %s' % (geom))
            source_filepath = os.path.join(geomLoc,geom)
            dest_filepath = os.path.join(geomLoc,geom.replace('.gz',''))
            unzip_gz(source_filepath, dest_filepath) 
            cleanUpGeom.append(geom) # append to the clean up list so that after meshing is done, the unzipped file is removed
    print('\n\t\tUpdating geomDict...')
    for geom in cleanUpGeom:
        print('\t\t\tChanging %s to %s' % (geom,geom.replace('.gz','')))
        geomDict[geom.replace('.gz','')] = geomDict.pop(geom)

    return geomDict



def unzip_gz(source_filepath, dest_filepath):
    """
    Decompresses a .gz file to a specified destination file.

    Args:
        source_filepath (str): Path to the input .gz file.
        dest_filepath (str): Path where the uncompressed file will be saved.
    """
    with gzip.open(source_filepath, 'rb') as f_in:
        with open(dest_filepath, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

def geomToDict(fullCaseSetupDict):
    geomDict = {}
    geomColumnNames = ['scale','refinement','layers','expansion','wallmodel']
    #getting geometry list from geometry section
    try:
        geometryList = fullCaseSetupDict['GEOMETRY']['GEOM']
    except:
        print('ERROR! [GEOMETRY] section invalid!')
        exit()
    
    try:
        print('\t\tGetting geometry...')
        geometryList = geometryList[0].split('\n')
        nGeoms = len(geometryList)
        print('\t\t\tFound: %1.0f' % (nGeoms))
    except:
        print('ERROR! Geometry input invalid!')
        
    #splitting geoms into columns
    for geometry in geometryList:
        geometry = geometry.split(',')
        
        if len(geometry) != len(geomColumnNames) + 1:
            print('ERROR! Geometry input invalid! Insufficient options input for: %s' % (geometry[0]))
            exit()
        else:
            geometryName = geometry[0]
            if geometryName in geomDict.keys():
                print('ERROR! Duplicate geometry name found: %s' % (geometryName))
                exit()
            geomDict[geometryName] = {}
            n = 0
            while n < (len(geomColumnNames)):
                geomCol = geomColumnNames[n]
                geomDict[geometryName][geomCol] = geometry[n+1]
                n = n + 1
    
    
    return geomDict

def getTemplateType():
    global templateLoc, fidelityTemplateLoc
    fullCaseSetupDict = getFullCaseSetup()
    SETUP = fullCaseSetupDict['GLOBAL_REFINEMENT']['TEMPLATE_TYPE'][0].split('_')[0]
    templateLoc = "%s/%s" % (templateBaseLoc,SETUP)
    fidelityTemplateLoc = os.path.join(templateLoc,
                                   'defaultFidelity',
                                   fullCaseSetupDict['GLOBAL_REFINEMENT']['TEMPLATE_TYPE'][0].replace(SETUP+"_fidelity_",''))
    
    #checking if setup template exists
    if os.path.isdir(templateLoc):
        print('\n\tUsing %s setup template in path: %s' % (SETUP,templateLoc))
    else:
        print('ERROR! %s is not a valid setup template location!' % (templateLoc))
        exit()


def getGlobalDefaults():
    defaultDict = {}
    print('\n\tGetting global templates...')
    config = configparser.ConfigParser()
    config.optionxform = str
    config.read_file(open("%s/defaultSetup/defaultOrder" % (templateLoc)))
    configSections = config.sections()
    
    #get the order so that the when writing to the caseSetup file, orders will be right
    defaultOrder = np.array(config.items('DEFAULT_ORDER')[0])
    
    defaultOrder = defaultOrder[1].split(' ')
    defaultDict['MODULE_LINK'] = {}
    for file in defaultOrder:
        print('\t\t%s' % (file))
        defaultConfigRead = configparser.ConfigParser()
        defaultConfigRead.optionxform = str

        try:
            defaultConfigRead.read_file(open("%s/defaultSetup/%s" % (templateLoc,file)))
        except:
            print('ERROR! Default %s cannot be opened!' % (file))
            exit()
        defaultSections = defaultConfigRead.sections()
        
        for section in defaultSections:
            defaultDict[section] = {}
            defaultDict['MODULE_LINK'][file] = [section]
            defaultLine = np.array(defaultConfigRead.items(section))
            defaultVars = defaultLine[:,0]
            for i in range(len(defaultVars)):
                defaultDict[section][defaultVars[i]] = defaultLine[i,1].split(' ')
    return defaultDict

def getCaseSetupDefaultModules(caseSetupDict,defaultDict):  
    global updateCaseSetupFlag
    caseSetupKeys = caseSetupDict.keys()
    defaultDictKeys = defaultDict.keys()
    try:
        defaultSection = caseSetupDict['DEFAULTS']   
    except:
        print('\n\nERROR! caseSetup does not have [DEFAULTS] section! To generate a new caseSetup, use the --new flag.')
        exit()
    caseSetupModules = caseSetupDict['DEFAULTS']['DEFAULT_MODULES']
    defaultModules = defaultDict['MODULE_LINK']
    defaultModuleNames = defaultDict['MODULE_LINK'].keys()
    
    #check that modules are valid
    invalidModules = []
    for inputModule in caseSetupModules:
        if inputModule in defaultModuleNames:
            continue
        elif inputModule != '':
            invalidModules.append(inputModule)
    if len(invalidModules) > 0:
        
        print('\n\n\nERROR! The following modules are invalid: ')
        for invalidModule in invalidModules:
            print('\t' + invalidModule)
        exit()
        
    
    #init dict for casesetup to read
    fullCaseSetupDict = {}
    #init dict for casesetup to write back
    writeCaseSetupDict = {}
    
    #if loops for default modules if they are there or not
    for module in defaultModules:
        sectionName = defaultModules[module][0]
        if module in caseSetupModules and sectionName in caseSetupKeys:
            fullCaseSetupDict[sectionName] = {}
            fullCaseSetupDict[sectionName] = defaultDict[sectionName]    
        elif module in caseSetupModules and sectionName not in caseSetupKeys:
            fullCaseSetupDict[sectionName] = {}
            fullCaseSetupDict[sectionName] = defaultDict[sectionName]
        elif module not in caseSetupModules and sectionName in caseSetupKeys:
            fullCaseSetupDict[sectionName] = {}
            fullCaseSetupDict[sectionName] = caseSetupDict[sectionName]
            writeCaseSetupDict[sectionName] = {}
            writeCaseSetupDict[sectionName] = caseSetupDict[sectionName]
            
            caseSetupSectionVars = caseSetupDict[sectionName].keys()
            defaultSectionVars = defaultDict[sectionName].keys()
            for var in defaultSectionVars:
                if var in caseSetupSectionVars:
                    continue
                elif var not in caseSetupSectionVars:
                    writeCaseSetupDict[sectionName][var] = defaultDict[sectionName][var]
                    updateCaseSetupFlag = True
            
        elif module not in caseSetupModules and sectionName not in caseSetupKeys:
            fullCaseSetupDict[sectionName] = {}
            fullCaseSetupDict[sectionName] = defaultDict[sectionName]
            writeCaseSetupDict[sectionName] = {}
            writeCaseSetupDict[sectionName] = defaultDict[sectionName]
            updateCaseSetupFlag = True
        elif sectionName.startswith('POR'):
            writeCaseSetupDict[sectionName] = {}
            writeCaseSetupDict[sectionName] = caseSetupDict[sectionName]
        else:
            print('Some weird error happened!')
    
    
    #addon check sections
    
    for section in caseSetupKeys:
        if any(section.startswith(i) for i in addonKeyWords):
            writeCaseSetupDict[section] = {}
            writeCaseSetupDict[section] = caseSetupDict[section]
            fullCaseSetupDict[section] = {}
            fullCaseSetupDict[section] = caseSetupDict[section]
            
    return writeCaseSetupDict,fullCaseSetupDict

def getCaseSetup(defaultDict):

    print('\n\tReading caseSetup from case directory...')
    caseSetupConfig = configparser.ConfigParser()
    caseSetupConfig.optionxform = str
    #tries to read the caseSetup file, if it can't find it, it throws an error
    try:
        caseSetupConfig.read_file(open("%s/%s/caseSetup" % (path,case)))
    except Exception as e:
        print('\n\n\nERROR! caseSetup invalid!')
        print(e)
        sys.exit()
    caseSetupDict = {}
    caseSetupConfigSections = caseSetupConfig.sections()
    #getting the modules that are already there
    for section in caseSetupConfigSections:
            caseSetupLine = np.array(caseSetupConfig.items(section))
            if len(caseSetupLine[:]) < 1:
                updateCaseSetupFlag = True
            else:
                caseSetupDict[section] = {}
                caseSetupVars = caseSetupLine[:,0]
                for i in range(len(caseSetupVars)):
                    caseSetupDict[section][caseSetupVars[i]] = caseSetupLine[i,1].split(' ')
    
    writeCaseSetupDict,fullCaseSetupDict = getCaseSetupDefaultModules(caseSetupDict,defaultDict)
    
    return caseSetupDict,writeCaseSetupDict,fullCaseSetupDict

def getFullCaseSetup():
    '''
    same as getCaseSetup() but pulls in the existing fullCaseSetup output by caseSetup
    '''

    caseSetupConfig = configparser.ConfigParser()
    caseSetupConfig.optionxform = str
    #tries to read the caseSetup file, if it can't find it, it throws an error
    try:
        caseSetupConfig.read_file(open("%s/%s/fullCaseSetupDict" % (path,case)))
    except Exception as e:
        print('\n\n\nERROR! fullCaseSetup invalid, make sure to run caseSetup first!')
        print(e)
        sys.exit()
    caseSetupDict = {}
    caseSetupConfigSections = caseSetupConfig.sections()
    #getting the modules that are already there
    for section in caseSetupConfigSections:
            caseSetupLine = np.array(caseSetupConfig.items(section))
            if len(caseSetupLine[:]) < 1:
                updateCaseSetupFlag = True
            else:
                caseSetupDict[section] = {}
                caseSetupVars = caseSetupLine[:,0]
                for i in range(len(caseSetupVars)):
                    caseSetupDict[section][caseSetupVars[i]] = caseSetupLine[i,1].split(' ')
    return caseSetupDict


main()